# Generated by Django 4.2.16 on 2025-03-12 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('animal', 'Animal'), ('nature', 'Nature'), ('character', 'Character')], max_length=50)),
                ('prompt_text', models.TextField()),
            ],
        ),
    ]
