# Generated by Django 4.2.16 on 2025-03-18 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_artprompt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
